### ISSUE TITLE
[TinyMCE] XSS Protection

### ISSUE THREAD

**Issue by LeaVerou** [mavoweb/plugins#7]
_From @yonjah on May 17, 2017 15:5_

It seem like it is possible to inject code into commits -
https://mavo.io/demos/homepage/?lite=&homepage-storage=https%3A%2F%2Fgithub.com%2Fyonjah%2Fdata-1%2Fhomepage.json

Since you don't need any approval to send link to the preview page this means stored xss can be achieved without a major issue.
Even if the preview will only be available to owners this is still a major issue since if we assume most owners will not have basic programming skills and wont be able to manually review the commit going into the preview page with injected code will allow taking over the owner account

I know this project is still very young but it is probably something you'll want to address sooner than later.

_Copied from original issue: mavoweb/mavo#188_

**Comment by LeaVerou** [comment]
Ouch, thanks! This is only present on TinyMCE areas, right?

**Comment by LeaVerou** [comment]
Yup, after some digging around, it looks like it's a vulnerability of the TinyMCE plugin, and should be fixed there. Moving it there!

**Comment by yonjah** [comment]
I don't think this is TinyMCE issue.
I changed the json file directly on github so even if TinyMCE can sanitize
the input an attacker can bypass it on the client side.

Mavo need to sanitize the data before it is injected back to the DOM. There
are a few js libraries that can sanitize HTML only allowing specific tags
and attributes.

On 18 May 2017 6:57 am, "Lea Verou" <notifications@github.com> wrote:

Ouch, thanks! This is only present on TinyMCE areas, right?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mavoweb/plugins/issues/7#issuecomment-302254255>, or mute
the thread

**Comment by LeaVerou** [comment]
Oh, I wasn't saying it's a TinyMCE issue, just that it's an issue with the TinyMCE Mavo plugin.
TinyMCE is the only editing widget that actually uses `innerHTML`. Everything else uses `textContent` or `setAttribute`.
The Markdown plugin also uses innerHTML, but after it's gone through the markdown parser/serializer, which AFAIK santizes it too.

**Comment by yonjah** [comment]
Oh sorry. I misunderstood what you meant. 
I still haven't had a chance to look how Mavo works internally, but it looks like a really awesome project :-)

When you implement a solution you might wanna consider instead of filtering out XSS on display, to only detect it and not displaying the string at all. You can notify the user something weird is going on (and maybe suggesting opening an issue if he thinks the detection got it wrong).
 
There's an js-xss project which might be useful - https://github.com/leizongmin/js-xss
But using strings inside html attributes might need a different solution.

**Comment by LeaVerou** [comment]
I know that TinyMCE has HTML sanitization code, so hopefully that's exposed somehow so Mavo can use it too. Otherwise, I guess I'll have to include another dependency in that plugin.

Why only detect it? Because we're not sure filtering it out will work correctly?

I believe attributes should be safe, unless they’re `on*` attributes, but that can easily be avoided by the author (and I believe expressions are even disabled inside those attributes, so it's only if the author uses e.g. `mv-attribute="onclick"`, but why on earth would they do that.

**Comment by yonjah** [comment]
Yea filtering is hard to get right. 
I think a common open source filtering library will probably get it right but there is always the chance it will miss something.

The thing is if we know we are only creating XSS free content (we filter and escape everything that needs to be escaped before we save the data to the endpoint) than when we come to display the content if filtering it still finds stuff to remove and change we can assume someone is trying to mess things up. We can trust escaping and the filter to work again, but why would we anyway display something we detected as malice ?

The thing with attributes is that you need to escape attributes you would normally allow in html like commas
So while if you have an img src which is `someimage.jpg" onload="alert(1);` then when injected it might 
actually create the onload attribute. Again I don't know how Mavo handles this. Using `setAttribute` with this input will probably be fine, but if your having server side rendering or some other templating engine which will create the tag with attributes in one go ,you might need to escape it (but escaping commas is simple and easy fix for this issue).

The other issue is the anchor tag `href` attribute which can contain 'javascript:' to execute scripts instead of going to a link (again an easy fix especially if you don't care about filtering and just block every url that doesn't start with http/ftp/https)

And as you said with the on* attributes they are intended to run JS so if someone allows to change them there is not much you can do. You might wanna block them so Mavo will just not allow binding to them. If someone actually asks to use this attributes you there are ways to accommodate for that but as you said no one with his right mind will ever do that

Any way don't take me on my word for it I might be missing some other injection vectors.
With framework that do HTML parsing there is always the chance of actually injecting Mavo specific command into the HTML and have it executed (Angular 1.5 had similar issue which got it banned from being used in firefox extensions) From the little I understand about Mavo that shouldn't be possible but I know nothing about it's internal so you might want to verify that as well.

**Comment by LeaVerou** [comment]
> The thing is if we know we are only creating XSS free content (we filter and escape everything that needs to be escaped before we save the data to the endpoint) than when we come to display the content if filtering it still finds stuff to remove and change we can assume someone is trying to mess things up. We can trust escaping and the filter to work again, but why would we anyway display something we detected as malice ?

I’m not sure every instance of a `<script>` tag in the data is malice. It could be someone trying to customize the page, or just a beginner experimenting with what's allowed. 

> Using setAttribute with this input will probably be fine, 

it is. :)

> but if your having server side rendering or some other templating engine which will create the tag with attributes in one go ,you might need to escape it (but escaping commas is simple and easy fix for this issue).

Let's cross that bridge when we get to it. Mavo doesn't currently have a server-side component, and even if it did, it would use a parser.

> The other issue is the anchor tag href attribute which can contain 'javascript:' to execute scripts instead of going to a link (again an easy fix especially if you don't care about filtering and just block every url that doesn't start with http/ftp/https)

Good point! I’m not sure that's a significant danger, if I click on a link without checking where it goes, all sorts of things could happen. Anyhow, I don't see a downside with blocking that when editing an `<a>` element. Not sure it's sensible to block it with expressions too though.

> With framework that do HTML parsing there is always the chance of actually injecting Mavo specific command into the HTML and have it executed

As long as we use text-only DOM methods like `textContent` and `setAttribute` there are very few ways this can happen. I should go through the Mavo codebase and make sure we're not using `innerHTML` somewhere.

`iframe@src` and `iframe@srcdoc` are also portentially unsafe, but it depends on what the author is trying to do. Mavo needs to be secure, but I don't want to cross over to protecting people against themselves too much.
